// <auto-generated />
using System;
using LinuxGameCompat.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LinuxGameCompat.Migrations
{
    [DbContext(typeof(CompatibilityDbContext))]
    partial class CompatibilityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LinuxGameCompat.Data.EvidenceClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ClaimValue")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SourceReferenceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SourceReferenceId");

                    b.ToTable("EvidenceClaims");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimText = "Community reports indicate the game is playable through Proton.",
                            ClaimType = "Status",
                            ClaimValue = "playable",
                            ObservedAt = new DateTimeOffset(new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SourceReferenceId = 1
                        },
                        new
                        {
                            Id = 2,
                            ClaimText = "Anti-cheat support is a compatibility consideration for multiplayer sessions.",
                            ClaimType = "Caveat",
                            ClaimValue = "anti-cheat",
                            ObservedAt = new DateTimeOffset(new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SourceReferenceId = 3
                        },
                        new
                        {
                            Id = 3,
                            ClaimText = "Anti-cheat policy blocks Linux/Proton play.",
                            ClaimType = "Status",
                            ClaimValue = "unsupported",
                            ObservedAt = new DateTimeOffset(new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SourceReferenceId = 4
                        });
                });

            modelBuilder.Entity("LinuxGameCompat.Data.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompatibilityStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.Property<int?>("SteamAppId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("SteamAppId")
                        .IsUnique()
                        .HasFilter("\"SteamAppId\" IS NOT NULL");

                    b.HasIndex("IsHidden", "Title");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompatibilityStatus = "Playable",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsHidden = false,
                            Slug = "baldurs-gate-3",
                            SteamAppId = 1086940,
                            Title = "Baldur's Gate 3",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2,
                            CompatibilityStatus = "PlayableWithCaveats",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsHidden = false,
                            Slug = "helldivers-2",
                            SteamAppId = 553850,
                            Title = "Helldivers 2",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 3,
                            CompatibilityStatus = "Unsupported",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsHidden = false,
                            Slug = "destiny-2",
                            SteamAppId = 1085660,
                            Title = "Destiny 2",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 4,
                            CompatibilityStatus = "Unknown",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsHidden = false,
                            Slug = "unnamed-prototype",
                            Title = "Unnamed Prototype",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 5,
                            CompatibilityStatus = "Unknown",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsHidden = true,
                            Slug = "suppressed-test-record",
                            SteamAppId = 999001,
                            Title = "Suppressed Test Record",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("LinuxGameCompat.Data.GameCompatibilitySummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("EvidenceHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EvidenceVersion")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsStale")
                        .HasColumnType("boolean");

                    b.Property<string>("Model")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Provider")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("SummaryStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("SummaryText")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .IsUnique();

                    b.ToTable("GameCompatibilitySummaries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EvidenceHash = "seed-baldurs-gate-3-v1",
                            EvidenceVersion = "seed-v1",
                            GameId = 1,
                            GeneratedAt = new DateTimeOffset(new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsStale = false,
                            Model = "manual-baseline",
                            Provider = "placeholder",
                            State = "Current",
                            SummaryStatus = "Playable",
                            SummaryText = "Playable through Proton based on stored source-backed evidence."
                        },
                        new
                        {
                            Id = 2,
                            EvidenceHash = "seed-helldivers-2-v1",
                            EvidenceVersion = "seed-v1",
                            GameId = 2,
                            IsStale = true,
                            State = "NotGenerated",
                            SummaryStatus = "PlayableWithCaveats"
                        });
                });

            modelBuilder.Entity("LinuxGameCompat.Data.SourceReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("SourceGameId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("SourceSystemId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("Url");

                    b.HasIndex("SourceSystemId", "SourceGameId")
                        .IsUnique();

                    b.ToTable("SourceReferences");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            GameId = 1,
                            MetadataJson = "{\"source\":\"protondb\",\"kind\":\"steam-app\"}",
                            SourceGameId = "1086940",
                            SourceSystemId = 1,
                            Url = "https://www.protondb.com/app/1086940"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            GameId = 2,
                            MetadataJson = "{\"source\":\"protondb\",\"kind\":\"steam-app\"}",
                            SourceGameId = "553850",
                            SourceSystemId = 1,
                            Url = "https://www.protondb.com/app/553850"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            GameId = 2,
                            MetadataJson = "{\"source\":\"areweanticheatyet\",\"kind\":\"game-page\"}",
                            SourceGameId = "helldivers-2",
                            SourceSystemId = 2,
                            Url = "https://areweanticheatyet.com/game/helldivers-2"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            GameId = 3,
                            MetadataJson = "{\"source\":\"areweanticheatyet\",\"kind\":\"game-page\"}",
                            SourceGameId = "destiny-2",
                            SourceSystemId = 2,
                            Url = "https://areweanticheatyet.com/game/destiny-2"
                        });
                });

            modelBuilder.Entity("LinuxGameCompat.Data.SourceSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("SourceSystems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseUrl = "https://www.protondb.com",
                            Name = "ProtonDB",
                            Type = "ProtonDb"
                        },
                        new
                        {
                            Id = 2,
                            BaseUrl = "https://areweanticheatyet.com",
                            Name = "Are We Anti-Cheat Yet?",
                            Type = "AreWeAntiCheatYet"
                        });
                });

            modelBuilder.Entity("LinuxGameCompat.Data.EvidenceClaim", b =>
                {
                    b.HasOne("LinuxGameCompat.Data.SourceReference", "SourceReference")
                        .WithMany("EvidenceClaims")
                        .HasForeignKey("SourceReferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceReference");
                });

            modelBuilder.Entity("LinuxGameCompat.Data.GameCompatibilitySummary", b =>
                {
                    b.HasOne("LinuxGameCompat.Data.Game", "Game")
                        .WithOne("CompatibilitySummary")
                        .HasForeignKey("LinuxGameCompat.Data.GameCompatibilitySummary", "GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("LinuxGameCompat.Data.SourceReference", b =>
                {
                    b.HasOne("LinuxGameCompat.Data.Game", "Game")
                        .WithMany("SourceReferences")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LinuxGameCompat.Data.SourceSystem", "SourceSystem")
                        .WithMany("SourceReferences")
                        .HasForeignKey("SourceSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("SourceSystem");
                });

            modelBuilder.Entity("LinuxGameCompat.Data.Game", b =>
                {
                    b.Navigation("CompatibilitySummary");

                    b.Navigation("SourceReferences");
                });

            modelBuilder.Entity("LinuxGameCompat.Data.SourceReference", b =>
                {
                    b.Navigation("EvidenceClaims");
                });

            modelBuilder.Entity("LinuxGameCompat.Data.SourceSystem", b =>
                {
                    b.Navigation("SourceReferences");
                });
#pragma warning restore 612, 618
        }
    }
}
